import type { AgentControlState } from './agentControlTypes';

export const mockAgentControlState: AgentControlState = {
  identity: {
    id: 'jarvis-primary',
    name: 'Jarvis Prime',
    status: 'working',
    provider: 'OpenAI',
    model: 'GPT-5.2',
    profile: 'home-operator',
    activeProfileLabel: 'Household command operator',
    connection: 'online',
    lastConnectedAt: '2026-05-22T17:58:00.000Z',
    currentTask: 'Monitoring command approvals, live telemetry, and workspace changes.',
  },
  usage: {
    requestCount: 184,
    approvedActionCount: 31,
    rejectedActionCount: 4,
    blockedActionCount: 7,
    estimatedTokens: 428_600,
    estimatedCostUsd: 14.82,
    windowStartedAt: '2026-05-22T00:00:00.000Z',
  },
  jobs: [
    {
      id: 'job-nightly-health',
      name: 'Nightly system health scan',
      kind: 'cron',
      status: 'active',
      cadence: 'Daily at 02:15',
      lastRunAt: '2026-05-22T02:15:00.000Z',
      nextRunAt: '2026-05-23T02:15:00.000Z',
      owner: 'Jarvis Prime',
      safeForHome: true,
      description: 'Checks integrations, stale widgets, and command queue drift.',
      visibleTo: ['admin', 'support', 'home'],
    },
    {
      id: 'job-approval-watch',
      name: 'Approval queue watcher',
      kind: 'monitor',
      status: 'active',
      cadence: 'Every 5 minutes',
      lastRunAt: '2026-05-22T18:00:00.000Z',
      nextRunAt: '2026-05-22T18:05:00.000Z',
      owner: 'Command inbox',
      safeForHome: true,
      description: 'Surfaces pending proposals and unsafe command attempts.',
      visibleTo: ['admin', 'support', 'home'],
    },
    {
      id: 'job-network-repair',
      name: 'Tailnet repair monitor',
      kind: 'automation',
      status: 'paused',
      cadence: 'On degraded heartbeat',
      lastRunAt: '2026-05-21T20:40:00.000Z',
      nextRunAt: 'Paused',
      owner: 'Support profile',
      safeForHome: false,
      description: 'Collects diagnostics and prepares repair suggestions for support.',
      visibleTo: ['admin', 'support'],
    },
    {
      id: 'job-permission-audit',
      name: 'Permission drift audit',
      kind: 'cron',
      status: 'failed',
      cadence: 'Weekly on Friday',
      lastRunAt: '2026-05-22T06:00:00.000Z',
      nextRunAt: '2026-05-29T06:00:00.000Z',
      owner: 'Security watch',
      safeForHome: false,
      description: 'Compares requested tool access against high-risk action gates.',
      visibleTo: ['admin', 'support'],
    },
  ],
  permissions: [
    {
      id: 'perm-workspace-read',
      label: 'Read workspace state',
      category: 'workspace',
      level: 'read',
      risk: 'low',
      description: 'Inspect open widgets, workspace placement, and visible shell state.',
      visibleTo: ['admin', 'support', 'home'],
    },
    {
      id: 'perm-command-propose',
      label: 'Propose command actions',
      category: 'commands',
      level: 'suggest',
      risk: 'medium',
      description: 'Create approval requests in Command inbox before any action runs.',
      visibleTo: ['admin', 'support', 'home'],
    },
    {
      id: 'perm-automation-control',
      label: 'Manage automations',
      category: 'automation',
      level: 'execute',
      risk: 'high',
      description: 'Create, pause, or change recurring jobs after an admin approval.',
      visibleTo: ['admin', 'support'],
    },
    {
      id: 'perm-network-exec',
      label: 'Network repair commands',
      category: 'network',
      level: 'blocked',
      risk: 'high',
      description: 'Direct network mutations are blocked until backend enforcement is connected.',
      visibleTo: ['admin', 'support'],
    },
    {
      id: 'perm-file-read',
      label: 'Read approved local files',
      category: 'files',
      level: 'read',
      risk: 'medium',
      description: 'Read files explicitly imported into the workspace file explorer.',
      visibleTo: ['admin', 'support', 'home'],
    },
  ],
  activity: [
    {
      id: 'activity-approval-schedule',
      kind: 'proposal',
      title: 'Proposed schedule repair',
      detail: 'Asked to move a safe household automation to the next maintenance window.',
      timestamp: '2026-05-22T17:57:00.000Z',
      source: 'Command inbox',
      status: 'sent',
      visibleTo: ['admin', 'support', 'home'],
    },
    {
      id: 'activity-command-approved',
      kind: 'approval',
      title: 'Approved telemetry refresh',
      detail: 'Admin approved a low-risk telemetry refresh action.',
      timestamp: '2026-05-22T17:42:00.000Z',
      source: 'Command inbox',
      status: 'approved',
      visibleTo: ['admin', 'support'],
    },
    {
      id: 'activity-permission-blocked',
      kind: 'failure',
      title: 'Blocked network mutation',
      detail: 'A direct network repair request was blocked by high-risk gates.',
      timestamp: '2026-05-22T16:55:00.000Z',
      source: 'Permission gate',
      status: 'blocked',
      visibleTo: ['admin', 'support'],
    },
    {
      id: 'activity-reconnect',
      kind: 'connection',
      title: 'Agent heartbeat restored',
      detail: 'Agent control mock channel reported an online heartbeat.',
      timestamp: '2026-05-22T16:30:00.000Z',
      source: 'Agent transport',
      status: 'active',
      visibleTo: ['admin', 'support', 'home'],
    },
  ],
  version: 1,
  updatedAt: '2026-05-22T18:00:00.000Z',
};
