import type { AgentControlState } from './agentControlTypes';

export const mockAgentControlState: AgentControlState = {
  identity: {
    id: 'jarvis-primary',
    name: 'Jarvis Prime',
    status: 'working',
    provider: 'OpenAI',
    model: 'GPT-5.2',
    profile: 'home-operator',
    activeProfileLabel: 'Household command operator',
    connection: 'online',
    lastConnectedAt: '2026-05-22T17:58:00.000Z',
    currentTask: 'Monitoring command approvals, live telemetry, and workspace changes.',
  },
  activeAgentId: 'jarvis-primary',
  activeConnectorId: 'mock-agent-runtime',
  eventStreamStatus: 'idle',
  lastBridgeEventAt: null,
  diagnostics: [
    {
      id: 'diagnostic-mock-fallback',
      connectorId: 'mock-agent-runtime',
      level: 'info',
      message: 'Mock fallback is active until a Hermes or OpenClaw bridge responds.',
      source: 'runtime',
      timestamp: '2026-05-22T17:58:00.000Z',
    },
  ],
  connectors: [
    {
      id: 'hermes-local-bridge',
      provider: 'hermes',
      kind: 'local',
      url: 'http://127.0.0.1:8787',
      status: 'offline',
      lastSeenAt: null,
      capabilities: ['chat', 'tool-proposals', 'local-automation', 'voice-events'],
      error: 'Local Hermes bridge not detected.',
    },
    {
      id: 'openclaw-local-bridge',
      provider: 'openclaw',
      kind: 'local',
      url: 'http://127.0.0.1:8797',
      status: 'offline',
      lastSeenAt: null,
      capabilities: ['multi-agent', 'workflow-planning', 'tool-proposals'],
      error: 'OpenClaw bridge not detected.',
    },
    {
      id: 'agent-remote-bridge',
      provider: 'custom',
      kind: 'remote',
      url: null,
      status: 'not-configured',
      lastSeenAt: null,
      capabilities: ['hosted-agent', 'sync'],
      error: 'Advanced custom bridge is not configured.',
    },
    {
      id: 'mock-agent-runtime',
      provider: 'openai',
      kind: 'mock',
      url: null,
      status: 'connected',
      lastSeenAt: '2026-05-22T17:58:00.000Z',
      capabilities: ['mock-proposals', 'local-audit', 'role-gates'],
      error: null,
    },
  ],
  agents: [
    {
      id: 'jarvis-primary',
      name: 'Jarvis Prime',
      specialty: 'coordinator',
      provider: 'OpenAI',
      model: 'GPT-5.2',
      profile: 'home-operator',
      status: 'working',
      connection: 'online',
      summary: 'Coordinates user objectives, agent proposals, workflow runs, and command approvals.',
      visibleTo: ['admin', 'support', 'home'],
    },
    {
      id: 'jarvis-support',
      name: 'Jarvis Support',
      specialty: 'support',
      provider: 'OpenAI',
      model: 'GPT-5.2',
      profile: 'support-diagnostics',
      status: 'available',
      connection: 'online',
      summary: 'Prepares diagnostics, repair suggestions, and degraded integration checks.',
      visibleTo: ['admin', 'support'],
    },
    {
      id: 'jarvis-security',
      name: 'Jarvis Security',
      specialty: 'security',
      provider: 'OpenAI',
      model: 'GPT-5.2',
      profile: 'security-watch',
      status: 'waiting',
      connection: 'degraded',
      summary: 'Reviews high-risk proposals, permission drift, and security-sensitive workflows.',
      visibleTo: ['admin', 'support'],
    },
    {
      id: 'jarvis-home',
      name: 'Jarvis Home',
      specialty: 'home',
      provider: 'OpenAI',
      model: 'GPT-5.2 mini',
      profile: 'home-operator',
      status: 'available',
      connection: 'online',
      summary: 'Handles safe household routines and comfort-oriented automations.',
      visibleTo: ['admin', 'home'],
    },
    {
      id: 'jarvis-workflow',
      name: 'Jarvis Workflow',
      specialty: 'workflow',
      provider: 'OpenAI',
      model: 'GPT-5.2',
      profile: 'support-diagnostics',
      status: 'available',
      connection: 'online',
      summary: 'Turns saved workflows into executable runbooks and approval-ready steps.',
      visibleTo: ['admin', 'support', 'home'],
    },
  ],
  usage: {
    requestCount: 184,
    approvedActionCount: 31,
    rejectedActionCount: 4,
    blockedActionCount: 7,
    estimatedTokens: 428_600,
    estimatedCostUsd: 14.82,
    windowStartedAt: '2026-05-22T00:00:00.000Z',
  },
  jobs: [
    {
      id: 'job-nightly-health',
      name: 'Nightly system health scan',
      kind: 'cron',
      status: 'active',
      cadence: 'Daily at 02:15',
      lastRunAt: '2026-05-22T02:15:00.000Z',
      nextRunAt: '2026-05-23T02:15:00.000Z',
      owner: 'Jarvis Prime',
      safeForHome: true,
      description: 'Checks integrations, stale widgets, and command queue drift.',
      visibleTo: ['admin', 'support', 'home'],
    },
    {
      id: 'job-approval-watch',
      name: 'Approval queue watcher',
      kind: 'monitor',
      status: 'active',
      cadence: 'Every 5 minutes',
      lastRunAt: '2026-05-22T18:00:00.000Z',
      nextRunAt: '2026-05-22T18:05:00.000Z',
      owner: 'Command inbox',
      safeForHome: true,
      description: 'Surfaces pending proposals and unsafe command attempts.',
      visibleTo: ['admin', 'support', 'home'],
    },
    {
      id: 'job-network-repair',
      name: 'Tailnet repair monitor',
      kind: 'automation',
      status: 'paused',
      cadence: 'On degraded heartbeat',
      lastRunAt: '2026-05-21T20:40:00.000Z',
      nextRunAt: 'Paused',
      owner: 'Support profile',
      safeForHome: false,
      description: 'Collects diagnostics and prepares repair suggestions for support.',
      visibleTo: ['admin', 'support'],
    },
    {
      id: 'job-permission-audit',
      name: 'Permission drift audit',
      kind: 'cron',
      status: 'failed',
      cadence: 'Weekly on Friday',
      lastRunAt: '2026-05-22T06:00:00.000Z',
      nextRunAt: '2026-05-29T06:00:00.000Z',
      owner: 'Security watch',
      safeForHome: false,
      description: 'Compares requested tool access against high-risk action gates.',
      visibleTo: ['admin', 'support'],
    },
  ],
  permissions: [
    {
      id: 'perm-workspace-read',
      label: 'Read workspace state',
      category: 'workspace',
      level: 'read',
      risk: 'low',
      description: 'Inspect open widgets, workspace placement, and visible shell state.',
      visibleTo: ['admin', 'support', 'home'],
    },
    {
      id: 'perm-command-propose',
      label: 'Propose command actions',
      category: 'commands',
      level: 'suggest',
      risk: 'medium',
      description: 'Create approval requests in Command inbox before any action runs.',
      visibleTo: ['admin', 'support', 'home'],
    },
    {
      id: 'perm-automation-control',
      label: 'Manage automations',
      category: 'automation',
      level: 'execute',
      risk: 'high',
      description: 'Create, pause, or change recurring jobs after an admin approval.',
      visibleTo: ['admin', 'support'],
    },
    {
      id: 'perm-network-exec',
      label: 'Network repair commands',
      category: 'network',
      level: 'blocked',
      risk: 'high',
      description: 'Direct network mutations are blocked until backend enforcement is connected.',
      visibleTo: ['admin', 'support'],
    },
    {
      id: 'perm-file-read',
      label: 'Read approved local files',
      category: 'files',
      level: 'read',
      risk: 'medium',
      description: 'Read files explicitly imported into the workspace file explorer.',
      visibleTo: ['admin', 'support', 'home'],
    },
  ],
  activity: [
    {
      id: 'activity-approval-schedule',
      kind: 'proposal',
      title: 'Proposed schedule repair',
      detail: 'Asked to move a safe household automation to the next maintenance window.',
      timestamp: '2026-05-22T17:57:00.000Z',
      source: 'Command inbox',
      status: 'sent',
      visibleTo: ['admin', 'support', 'home'],
    },
    {
      id: 'activity-command-approved',
      kind: 'approval',
      title: 'Approved telemetry refresh',
      detail: 'Admin approved a low-risk telemetry refresh action.',
      timestamp: '2026-05-22T17:42:00.000Z',
      source: 'Command inbox',
      status: 'approved',
      visibleTo: ['admin', 'support'],
    },
    {
      id: 'activity-permission-blocked',
      kind: 'failure',
      title: 'Blocked network mutation',
      detail: 'A direct network repair request was blocked by high-risk gates.',
      timestamp: '2026-05-22T16:55:00.000Z',
      source: 'Permission gate',
      status: 'blocked',
      visibleTo: ['admin', 'support'],
    },
    {
      id: 'activity-reconnect',
      kind: 'connection',
      title: 'Agent heartbeat restored',
      detail: 'Agent control mock channel reported an online heartbeat.',
      timestamp: '2026-05-22T16:30:00.000Z',
      source: 'Agent transport',
      status: 'active',
      visibleTo: ['admin', 'support', 'home'],
    },
  ],
  version: 1,
  updatedAt: '2026-05-22T18:00:00.000Z',
};
